#!/usr/bin/env bash
# A Bash script that display Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

a=0

while [ $a -lt 10 ]
do
    if [[ "$a" == '9' ]]; then
    echo 'Hi'
    fi
    echo "Best School"
    (( a++ ))
done
